local objects = {
  {
    id = 1,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 207.167,
    y = 47.8333,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 3,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 144.667,
    y = 241,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 4,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 192.667,
    y = 224.333,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 5,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 270.667,
    y = 272.333,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 6,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 304.167,
    y = 270.833,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 7,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 401,
    y = 257,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 8,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 512.5,
    y = 179.5,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 9,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 288,
    y = 146,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 11,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 383,
    y = 161,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 12,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 129,
    y = 144,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 13,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 175.5,
    y = 143.5,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 15,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 351,
    y = 47.5,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 16,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 607,
    y = 177,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 17,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 655.5,
    y = 175.5,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 18,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 623.5,
    y = 48.5,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 19,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 543.5,
    y = 32,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 20,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 79.5,
    y = 34,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 21,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 463,
    y = 62.5,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  },
  {
    id = 22,
    name = "Gem",
    type = "",
    shape = "rectangle",
    x = 32.5,
    y = 255,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 23,
    name = "Gem",
    type = "",
    shape = "rectangle",
    x = 767,
    y = 80,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 24,
    name = "Gem",
    type = "",
    shape = "rectangle",
    x = 511,
    y = 33.5,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 25,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 65.5,
    y = 257,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 53,
    visible = true,
    properties = {}
  }
}


return objects